name: Publish
on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup java
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          architecture: x64
          distribution: oracle
          cache: 'gradle'
      - name: Publish
        run: ./gradlew publishToCentralPortal
        env:
          SIGNING_PASSPHRASE: ${{ secrets.SIGNING_PASSPHRASE }}
          SIGNING_SECRETKEY: ${{ secrets.SIGNING_SECRETKEY }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          LIBRARY_GROUP: ${{ env.LIBRARY_GROUP }}
          SIGNING_KEYID: ${{ env.SIGNING_KEYID }}